### ISSUE TITLE
Incorrect file path parsing if path contains spaces

### ISSUE THREAD

**Issue by AndesVL** [AndesVL/vscode-racket-repl#13]
Maybe, I just found a little further bug related to OneDrive! 😢

Probably it is due to spaces included in a folder name of the directory path (......\OneDrive - Middlesex University\\.....)
![BugFound](https://user-images.githubusercontent.com/57289592/68230121-6435eb80-fff0-11e9-8ce6-4ef23cd40f69.png)

_Originally posted by @Francy93 in https://github.com/AndesVL/vscode-racket-repl/issues/11#issuecomment-549921964_

**Comment by AndesVL** [comment]
Reproducible on windows

**Comment by Francy93** [comment]
The new version is working greatly sofar! :)
However, there's some functionality to upgrade in the next version.

Here the first suggestion:
As a future enhancement, it would result useful to remove the need to save every time before running the terminal.

We can't wait to try subsequent versions 🤩

**Comment by Francy93** [comment]
One more potential improvement reported for the next version:
The terminal doesn't allow to copy and paste.

![issue](https://user-images.githubusercontent.com/57289592/68504914-04447c80-025e-11ea-87e1-b239a623784f.png)
