### ISSUE TITLE
The Terminal Process Termintated With Exit Code 1

### ISSUE THREAD

**Issue by jcolivo** [AndesVL/vscode-racket-repl#4]
Hello, and tank you for developing the Racket REPL for VSCode!

I am using a Windows computer, and ran into this problem with the error code in the subject line:
`C:\Users\%user%\.vscode\extensions\andes.racket-repl-1.3.0\out>./launch_windows.bat C:/Users$user%/filename.rkt
'.' is not recognized as an internal or external command, operable program or batch file.`

The solution for this is to remove the *nix run command './' before launch_windows.bat, and replace it with a space. I found that the REPL ran well when the following command was entered instead:
`C:\Users\%user%\.vscode\extensions\andes.racket-repl-1.3.0\out> launch_windows.bat C:/Users$user%/filename.rkt`

I couldn't find the file to correct this, but I know you are the one who can :-).

Thank you!

**Comment by Donaim** [comment]
part that adds '.' before script name: https://github.com/AndesVL/vscode-racket-repl/blob/master/src/replManager.ts#L87

**Comment by AndesVL** [comment]
It should work now, I noticed that I had no issues using PowerShell so I added a case to handle the (default) cmd shell's launch string. 

commit 1607ad993e887a18397c9b050ef4b26f7f4f9acc
